apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: easyschool.academy.com
spec:
  group: academy.com
  scope: Namespaced
  names:
    plural: easyschools
    singular: easyschool
    kind: Easyschool
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              color:
                type: string
              size:
                type: string
    selectableFields:
    - jsonPath: .spec.color
    - jsonPath: .spec.size
    additionalPrinterColumns:
    - jsonPath: .spec.color
      name: Color
      type: string
    - jsonPath: .spec.size
      name: Size
      type: string

